# Generated by Django 4.2.3 on 2023-08-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_alter_attendance_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackstudent',
            name='feedback',
            field=models.TextField(default='t'),
            preserve_default=False,
        ),
    ]
